// AUTO-GENERATED by scripts/gen-geo.cjs from the CLDR-derived `countries-list` dataset.
// Do not edit by hand. Global country + language reference for a worldwide audience.
// 252 countries · 185 languages.

export interface CountryInfo {
  code: string;          // ISO 3166-1 alpha-2 (e.g. "KE", "US", "IN")
  name: string;          // English name
  native: string;        // native name
  callingCode: number;   // E.164 country calling code (e.g. 254, 1, 91)
  flag: string;          // flag emoji
  continent: string;     // continent code (AF, EU, AS, NA, SA, OC, AN)
  continentName: string;
  languages: string[];   // ISO 639-1 codes spoken/official in the country
}

export interface LanguageInfo {
  code: string;   // ISO 639-1 (e.g. "en", "sw", "ar")
  name: string;   // English name
  native: string; // native name (e.g. "Kiswahili", "العربية")
  rtl: boolean;   // right-to-left script
}

export const COUNTRIES: readonly CountryInfo[] = [
  {
    "code": "AF",
    "name": "Afghanistan",
    "native": "افغانستان",
    "callingCode": 93,
    "flag": "🇦🇫",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "ps",
      "fa",
      "uz",
      "tk"
    ]
  },
  {
    "code": "AX",
    "name": "Aland",
    "native": "Åland",
    "callingCode": 358,
    "flag": "🇦🇽",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "sv"
    ]
  },
  {
    "code": "AL",
    "name": "Albania",
    "native": "Shqipëria",
    "callingCode": 355,
    "flag": "🇦🇱",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "sq"
    ]
  },
  {
    "code": "DZ",
    "name": "Algeria",
    "native": "الجزائر",
    "callingCode": 213,
    "flag": "🇩🇿",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "ar"
    ]
  },
  {
    "code": "AS",
    "name": "American Samoa",
    "native": "American Samoa",
    "callingCode": 1684,
    "flag": "🇦🇸",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "en",
      "sm"
    ]
  },
  {
    "code": "AD",
    "name": "Andorra",
    "native": "Andorra",
    "callingCode": 376,
    "flag": "🇦🇩",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "ca"
    ]
  },
  {
    "code": "AO",
    "name": "Angola",
    "native": "Angola",
    "callingCode": 244,
    "flag": "🇦🇴",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "pt"
    ]
  },
  {
    "code": "AI",
    "name": "Anguilla",
    "native": "Anguilla",
    "callingCode": 1264,
    "flag": "🇦🇮",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "en"
    ]
  },
  {
    "code": "AQ",
    "name": "Antarctica",
    "native": "Antarctica",
    "callingCode": 672,
    "flag": "🇦🇶",
    "continent": "AN",
    "continentName": "Antarctica",
    "languages": []
  },
  {
    "code": "AG",
    "name": "Antigua and Barbuda",
    "native": "Antigua and Barbuda",
    "callingCode": 1268,
    "flag": "🇦🇬",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "en"
    ]
  },
  {
    "code": "AR",
    "name": "Argentina",
    "native": "Argentina",
    "callingCode": 54,
    "flag": "🇦🇷",
    "continent": "SA",
    "continentName": "South America",
    "languages": [
      "es",
      "gn"
    ]
  },
  {
    "code": "AM",
    "name": "Armenia",
    "native": "Հայաստան",
    "callingCode": 374,
    "flag": "🇦🇲",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "hy",
      "ru"
    ]
  },
  {
    "code": "AW",
    "name": "Aruba",
    "native": "Aruba",
    "callingCode": 297,
    "flag": "🇦🇼",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "nl",
      "pa"
    ]
  },
  {
    "code": "AC",
    "name": "Ascension Island",
    "native": "Ascension Island",
    "callingCode": 247,
    "flag": "🇦🇨",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "en"
    ]
  },
  {
    "code": "AU",
    "name": "Australia",
    "native": "Australia",
    "callingCode": 61,
    "flag": "🇦🇺",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "en"
    ]
  },
  {
    "code": "AT",
    "name": "Austria",
    "native": "Österreich",
    "callingCode": 43,
    "flag": "🇦🇹",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "de"
    ]
  },
  {
    "code": "AZ",
    "name": "Azerbaijan",
    "native": "Azərbaycan",
    "callingCode": 994,
    "flag": "🇦🇿",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "az"
    ]
  },
  {
    "code": "BS",
    "name": "Bahamas",
    "native": "Bahamas",
    "callingCode": 1242,
    "flag": "🇧🇸",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "en"
    ]
  },
  {
    "code": "BH",
    "name": "Bahrain",
    "native": "‏البحرين",
    "callingCode": 973,
    "flag": "🇧🇭",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "ar"
    ]
  },
  {
    "code": "BD",
    "name": "Bangladesh",
    "native": "Bangladesh",
    "callingCode": 880,
    "flag": "🇧🇩",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "bn"
    ]
  },
  {
    "code": "BB",
    "name": "Barbados",
    "native": "Barbados",
    "callingCode": 1246,
    "flag": "🇧🇧",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "en"
    ]
  },
  {
    "code": "BY",
    "name": "Belarus",
    "native": "Беларусь",
    "callingCode": 375,
    "flag": "🇧🇾",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "be",
      "ru"
    ]
  },
  {
    "code": "BE",
    "name": "Belgium",
    "native": "België",
    "callingCode": 32,
    "flag": "🇧🇪",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "nl",
      "fr",
      "de"
    ]
  },
  {
    "code": "BZ",
    "name": "Belize",
    "native": "Belize",
    "callingCode": 501,
    "flag": "🇧🇿",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "en",
      "es"
    ]
  },
  {
    "code": "BJ",
    "name": "Benin",
    "native": "Bénin",
    "callingCode": 229,
    "flag": "🇧🇯",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "fr"
    ]
  },
  {
    "code": "BM",
    "name": "Bermuda",
    "native": "Bermuda",
    "callingCode": 1441,
    "flag": "🇧🇲",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "en"
    ]
  },
  {
    "code": "BT",
    "name": "Bhutan",
    "native": "ʼbrug-yul",
    "callingCode": 975,
    "flag": "🇧🇹",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "dz"
    ]
  },
  {
    "code": "BO",
    "name": "Bolivia",
    "native": "Bolivia",
    "callingCode": 591,
    "flag": "🇧🇴",
    "continent": "SA",
    "continentName": "South America",
    "languages": [
      "es",
      "ay",
      "qu"
    ]
  },
  {
    "code": "BQ",
    "name": "Bonaire",
    "native": "Bonaire",
    "callingCode": 5997,
    "flag": "🇧🇶",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "nl"
    ]
  },
  {
    "code": "BA",
    "name": "Bosnia and Herzegovina",
    "native": "Bosna i Hercegovina",
    "callingCode": 387,
    "flag": "🇧🇦",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "bs",
      "hr",
      "sr"
    ]
  },
  {
    "code": "BW",
    "name": "Botswana",
    "native": "Botswana",
    "callingCode": 267,
    "flag": "🇧🇼",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "en",
      "tn"
    ]
  },
  {
    "code": "BV",
    "name": "Bouvet Island",
    "native": "Bouvetøya",
    "callingCode": 47,
    "flag": "🇧🇻",
    "continent": "AN",
    "continentName": "Antarctica",
    "languages": [
      "no",
      "nb",
      "nn"
    ]
  },
  {
    "code": "BR",
    "name": "Brazil",
    "native": "Brasil",
    "callingCode": 55,
    "flag": "🇧🇷",
    "continent": "SA",
    "continentName": "South America",
    "languages": [
      "pt"
    ]
  },
  {
    "code": "IO",
    "name": "British Indian Ocean Territory",
    "native": "British Indian Ocean Territory",
    "callingCode": 246,
    "flag": "🇮🇴",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "en"
    ]
  },
  {
    "code": "VG",
    "name": "British Virgin Islands",
    "native": "British Virgin Islands",
    "callingCode": 1284,
    "flag": "🇻🇬",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "en"
    ]
  },
  {
    "code": "BN",
    "name": "Brunei",
    "native": "Negara Brunei Darussalam",
    "callingCode": 673,
    "flag": "🇧🇳",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "ms"
    ]
  },
  {
    "code": "BG",
    "name": "Bulgaria",
    "native": "България",
    "callingCode": 359,
    "flag": "🇧🇬",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "bg"
    ]
  },
  {
    "code": "BF",
    "name": "Burkina Faso",
    "native": "Burkina Faso",
    "callingCode": 226,
    "flag": "🇧🇫",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "fr",
      "ff"
    ]
  },
  {
    "code": "BI",
    "name": "Burundi",
    "native": "Burundi",
    "callingCode": 257,
    "flag": "🇧🇮",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "fr",
      "rn"
    ]
  },
  {
    "code": "KH",
    "name": "Cambodia",
    "native": "កម្ពុជា",
    "callingCode": 855,
    "flag": "🇰🇭",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "km"
    ]
  },
  {
    "code": "CM",
    "name": "Cameroon",
    "native": "Cameroon",
    "callingCode": 237,
    "flag": "🇨🇲",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "en",
      "fr"
    ]
  },
  {
    "code": "CA",
    "name": "Canada",
    "native": "Canada",
    "callingCode": 1,
    "flag": "🇨🇦",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "en",
      "fr"
    ]
  },
  {
    "code": "CV",
    "name": "Cape Verde",
    "native": "Cabo Verde",
    "callingCode": 238,
    "flag": "🇨🇻",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "pt"
    ]
  },
  {
    "code": "KY",
    "name": "Cayman Islands",
    "native": "Cayman Islands",
    "callingCode": 1345,
    "flag": "🇰🇾",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "en"
    ]
  },
  {
    "code": "CF",
    "name": "Central African Republic",
    "native": "Ködörösêse tî Bêafrîka",
    "callingCode": 236,
    "flag": "🇨🇫",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "fr",
      "sg"
    ]
  },
  {
    "code": "TD",
    "name": "Chad",
    "native": "Tchad",
    "callingCode": 235,
    "flag": "🇹🇩",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "fr",
      "ar"
    ]
  },
  {
    "code": "CL",
    "name": "Chile",
    "native": "Chile",
    "callingCode": 56,
    "flag": "🇨🇱",
    "continent": "SA",
    "continentName": "South America",
    "languages": [
      "es"
    ]
  },
  {
    "code": "CN",
    "name": "China",
    "native": "中国",
    "callingCode": 86,
    "flag": "🇨🇳",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "zh"
    ]
  },
  {
    "code": "CX",
    "name": "Christmas Island",
    "native": "Christmas Island",
    "callingCode": 61,
    "flag": "🇨🇽",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "en"
    ]
  },
  {
    "code": "CC",
    "name": "Cocos (Keeling) Islands",
    "native": "Cocos (Keeling) Islands",
    "callingCode": 61,
    "flag": "🇨🇨",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "en"
    ]
  },
  {
    "code": "CO",
    "name": "Colombia",
    "native": "Colombia",
    "callingCode": 57,
    "flag": "🇨🇴",
    "continent": "SA",
    "continentName": "South America",
    "languages": [
      "es"
    ]
  },
  {
    "code": "KM",
    "name": "Comoros",
    "native": "Komori",
    "callingCode": 269,
    "flag": "🇰🇲",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "ar",
      "fr"
    ]
  },
  {
    "code": "CK",
    "name": "Cook Islands",
    "native": "Cook Islands",
    "callingCode": 682,
    "flag": "🇨🇰",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "en"
    ]
  },
  {
    "code": "CR",
    "name": "Costa Rica",
    "native": "Costa Rica",
    "callingCode": 506,
    "flag": "🇨🇷",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "es"
    ]
  },
  {
    "code": "HR",
    "name": "Croatia",
    "native": "Hrvatska",
    "callingCode": 385,
    "flag": "🇭🇷",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "hr"
    ]
  },
  {
    "code": "CU",
    "name": "Cuba",
    "native": "Cuba",
    "callingCode": 53,
    "flag": "🇨🇺",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "es"
    ]
  },
  {
    "code": "CW",
    "name": "Curacao",
    "native": "Curaçao",
    "callingCode": 5999,
    "flag": "🇨🇼",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "nl",
      "pa",
      "en"
    ]
  },
  {
    "code": "CY",
    "name": "Cyprus",
    "native": "Κύπρος",
    "callingCode": 357,
    "flag": "🇨🇾",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "el",
      "tr",
      "hy"
    ]
  },
  {
    "code": "CZ",
    "name": "Czech Republic",
    "native": "Česká republika",
    "callingCode": 420,
    "flag": "🇨🇿",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "cs"
    ]
  },
  {
    "code": "CD",
    "name": "Democratic Republic of the Congo",
    "native": "République démocratique du Congo",
    "callingCode": 243,
    "flag": "🇨🇩",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "fr",
      "ln",
      "kg",
      "sw",
      "lu"
    ]
  },
  {
    "code": "DK",
    "name": "Denmark",
    "native": "Danmark",
    "callingCode": 45,
    "flag": "🇩🇰",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "da"
    ]
  },
  {
    "code": "DJ",
    "name": "Djibouti",
    "native": "Djibouti",
    "callingCode": 253,
    "flag": "🇩🇯",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "fr",
      "ar"
    ]
  },
  {
    "code": "DM",
    "name": "Dominica",
    "native": "Dominica",
    "callingCode": 1767,
    "flag": "🇩🇲",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "en"
    ]
  },
  {
    "code": "DO",
    "name": "Dominican Republic",
    "native": "República Dominicana",
    "callingCode": 1809,
    "flag": "🇩🇴",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "es"
    ]
  },
  {
    "code": "TL",
    "name": "East Timor",
    "native": "Timor-Leste",
    "callingCode": 670,
    "flag": "🇹🇱",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "pt"
    ]
  },
  {
    "code": "EC",
    "name": "Ecuador",
    "native": "Ecuador",
    "callingCode": 593,
    "flag": "🇪🇨",
    "continent": "SA",
    "continentName": "South America",
    "languages": [
      "es"
    ]
  },
  {
    "code": "EG",
    "name": "Egypt",
    "native": "مصر‎",
    "callingCode": 20,
    "flag": "🇪🇬",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "ar"
    ]
  },
  {
    "code": "SV",
    "name": "El Salvador",
    "native": "El Salvador",
    "callingCode": 503,
    "flag": "🇸🇻",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "es"
    ]
  },
  {
    "code": "GQ",
    "name": "Equatorial Guinea",
    "native": "Guinea Ecuatorial",
    "callingCode": 240,
    "flag": "🇬🇶",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "es",
      "fr"
    ]
  },
  {
    "code": "ER",
    "name": "Eritrea",
    "native": "ኤርትራ",
    "callingCode": 291,
    "flag": "🇪🇷",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "ti",
      "ar",
      "en"
    ]
  },
  {
    "code": "EE",
    "name": "Estonia",
    "native": "Eesti",
    "callingCode": 372,
    "flag": "🇪🇪",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "et"
    ]
  },
  {
    "code": "SZ",
    "name": "Eswatini",
    "native": "Eswatini",
    "callingCode": 268,
    "flag": "🇸🇿",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "en",
      "ss"
    ]
  },
  {
    "code": "ET",
    "name": "Ethiopia",
    "native": "ኢትዮጵያ",
    "callingCode": 251,
    "flag": "🇪🇹",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "am"
    ]
  },
  {
    "code": "FK",
    "name": "Falkland Islands",
    "native": "Falkland Islands",
    "callingCode": 500,
    "flag": "🇫🇰",
    "continent": "SA",
    "continentName": "South America",
    "languages": [
      "en"
    ]
  },
  {
    "code": "FO",
    "name": "Faroe Islands",
    "native": "Føroyar",
    "callingCode": 298,
    "flag": "🇫🇴",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "fo"
    ]
  },
  {
    "code": "FJ",
    "name": "Fiji",
    "native": "Fiji",
    "callingCode": 679,
    "flag": "🇫🇯",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "en",
      "fj",
      "hi",
      "ur"
    ]
  },
  {
    "code": "FI",
    "name": "Finland",
    "native": "Suomi",
    "callingCode": 358,
    "flag": "🇫🇮",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "fi",
      "sv"
    ]
  },
  {
    "code": "FR",
    "name": "France",
    "native": "France",
    "callingCode": 33,
    "flag": "🇫🇷",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "fr"
    ]
  },
  {
    "code": "GF",
    "name": "French Guiana",
    "native": "Guyane française",
    "callingCode": 594,
    "flag": "🇬🇫",
    "continent": "SA",
    "continentName": "South America",
    "languages": [
      "fr"
    ]
  },
  {
    "code": "PF",
    "name": "French Polynesia",
    "native": "Polynésie française",
    "callingCode": 689,
    "flag": "🇵🇫",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "fr"
    ]
  },
  {
    "code": "TF",
    "name": "French Southern Territories",
    "native": "Territoire des Terres australes et antarctiques fr",
    "callingCode": 262,
    "flag": "🇹🇫",
    "continent": "AN",
    "continentName": "Antarctica",
    "languages": [
      "fr"
    ]
  },
  {
    "code": "GA",
    "name": "Gabon",
    "native": "Gabon",
    "callingCode": 241,
    "flag": "🇬🇦",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "fr"
    ]
  },
  {
    "code": "GM",
    "name": "Gambia",
    "native": "Gambia",
    "callingCode": 220,
    "flag": "🇬🇲",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "en"
    ]
  },
  {
    "code": "GE",
    "name": "Georgia",
    "native": "საქართველო",
    "callingCode": 995,
    "flag": "🇬🇪",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "ka"
    ]
  },
  {
    "code": "DE",
    "name": "Germany",
    "native": "Deutschland",
    "callingCode": 49,
    "flag": "🇩🇪",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "de"
    ]
  },
  {
    "code": "GH",
    "name": "Ghana",
    "native": "Ghana",
    "callingCode": 233,
    "flag": "🇬🇭",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "en"
    ]
  },
  {
    "code": "GI",
    "name": "Gibraltar",
    "native": "Gibraltar",
    "callingCode": 350,
    "flag": "🇬🇮",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "en"
    ]
  },
  {
    "code": "GR",
    "name": "Greece",
    "native": "Ελλάδα",
    "callingCode": 30,
    "flag": "🇬🇷",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "el"
    ]
  },
  {
    "code": "GL",
    "name": "Greenland",
    "native": "Kalaallit Nunaat",
    "callingCode": 299,
    "flag": "🇬🇱",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "kl"
    ]
  },
  {
    "code": "GD",
    "name": "Grenada",
    "native": "Grenada",
    "callingCode": 1473,
    "flag": "🇬🇩",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "en"
    ]
  },
  {
    "code": "GP",
    "name": "Guadeloupe",
    "native": "Guadeloupe",
    "callingCode": 590,
    "flag": "🇬🇵",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "fr"
    ]
  },
  {
    "code": "GU",
    "name": "Guam",
    "native": "Guam",
    "callingCode": 1671,
    "flag": "🇬🇺",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "en",
      "ch",
      "es"
    ]
  },
  {
    "code": "GT",
    "name": "Guatemala",
    "native": "Guatemala",
    "callingCode": 502,
    "flag": "🇬🇹",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "es"
    ]
  },
  {
    "code": "GG",
    "name": "Guernsey",
    "native": "Guernsey",
    "callingCode": 44,
    "flag": "🇬🇬",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "en",
      "fr"
    ]
  },
  {
    "code": "GN",
    "name": "Guinea",
    "native": "Guinée",
    "callingCode": 224,
    "flag": "🇬🇳",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "fr",
      "ff"
    ]
  },
  {
    "code": "GW",
    "name": "Guinea-Bissau",
    "native": "Guiné-Bissau",
    "callingCode": 245,
    "flag": "🇬🇼",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "pt"
    ]
  },
  {
    "code": "GY",
    "name": "Guyana",
    "native": "Guyana",
    "callingCode": 592,
    "flag": "🇬🇾",
    "continent": "SA",
    "continentName": "South America",
    "languages": [
      "en"
    ]
  },
  {
    "code": "HT",
    "name": "Haiti",
    "native": "Haïti",
    "callingCode": 509,
    "flag": "🇭🇹",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "fr",
      "ht"
    ]
  },
  {
    "code": "HM",
    "name": "Heard Island and McDonald Islands",
    "native": "Heard Island and McDonald Islands",
    "callingCode": 61,
    "flag": "🇭🇲",
    "continent": "AN",
    "continentName": "Antarctica",
    "languages": [
      "en"
    ]
  },
  {
    "code": "HN",
    "name": "Honduras",
    "native": "Honduras",
    "callingCode": 504,
    "flag": "🇭🇳",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "es"
    ]
  },
  {
    "code": "HK",
    "name": "Hong Kong",
    "native": "香港",
    "callingCode": 852,
    "flag": "🇭🇰",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "zh",
      "en"
    ]
  },
  {
    "code": "HU",
    "name": "Hungary",
    "native": "Magyarország",
    "callingCode": 36,
    "flag": "🇭🇺",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "hu"
    ]
  },
  {
    "code": "IS",
    "name": "Iceland",
    "native": "Ísland",
    "callingCode": 354,
    "flag": "🇮🇸",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "is"
    ]
  },
  {
    "code": "IN",
    "name": "India",
    "native": "भारत",
    "callingCode": 91,
    "flag": "🇮🇳",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "hi",
      "en"
    ]
  },
  {
    "code": "ID",
    "name": "Indonesia",
    "native": "Indonesia",
    "callingCode": 62,
    "flag": "🇮🇩",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "id"
    ]
  },
  {
    "code": "IR",
    "name": "Iran",
    "native": "ایران",
    "callingCode": 98,
    "flag": "🇮🇷",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "fa"
    ]
  },
  {
    "code": "IQ",
    "name": "Iraq",
    "native": "العراق",
    "callingCode": 964,
    "flag": "🇮🇶",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "ar",
      "ku"
    ]
  },
  {
    "code": "IE",
    "name": "Ireland",
    "native": "Éire",
    "callingCode": 353,
    "flag": "🇮🇪",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "ga",
      "en"
    ]
  },
  {
    "code": "IM",
    "name": "Isle of Man",
    "native": "Isle of Man",
    "callingCode": 44,
    "flag": "🇮🇲",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "en",
      "gv"
    ]
  },
  {
    "code": "IL",
    "name": "Israel",
    "native": "יִשְׂרָאֵל",
    "callingCode": 972,
    "flag": "🇮🇱",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "he",
      "ar"
    ]
  },
  {
    "code": "IT",
    "name": "Italy",
    "native": "Italia",
    "callingCode": 39,
    "flag": "🇮🇹",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "it"
    ]
  },
  {
    "code": "CI",
    "name": "Ivory Coast",
    "native": "Côte d'Ivoire",
    "callingCode": 225,
    "flag": "🇨🇮",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "fr"
    ]
  },
  {
    "code": "JM",
    "name": "Jamaica",
    "native": "Jamaica",
    "callingCode": 1876,
    "flag": "🇯🇲",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "en"
    ]
  },
  {
    "code": "JP",
    "name": "Japan",
    "native": "日本",
    "callingCode": 81,
    "flag": "🇯🇵",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "ja"
    ]
  },
  {
    "code": "JE",
    "name": "Jersey",
    "native": "Jersey",
    "callingCode": 44,
    "flag": "🇯🇪",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "en",
      "fr"
    ]
  },
  {
    "code": "JO",
    "name": "Jordan",
    "native": "الأردن",
    "callingCode": 962,
    "flag": "🇯🇴",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "ar"
    ]
  },
  {
    "code": "KZ",
    "name": "Kazakhstan",
    "native": "Қазақстан",
    "callingCode": 7,
    "flag": "🇰🇿",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "kk",
      "ru"
    ]
  },
  {
    "code": "KE",
    "name": "Kenya",
    "native": "Kenya",
    "callingCode": 254,
    "flag": "🇰🇪",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "en",
      "sw"
    ]
  },
  {
    "code": "KI",
    "name": "Kiribati",
    "native": "Kiribati",
    "callingCode": 686,
    "flag": "🇰🇮",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "en"
    ]
  },
  {
    "code": "XK",
    "name": "Kosovo",
    "native": "Republika e Kosovës",
    "callingCode": 377,
    "flag": "🇽🇰",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "sq",
      "sr"
    ]
  },
  {
    "code": "KW",
    "name": "Kuwait",
    "native": "الكويت",
    "callingCode": 965,
    "flag": "🇰🇼",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "ar"
    ]
  },
  {
    "code": "KG",
    "name": "Kyrgyzstan",
    "native": "Кыргызстан",
    "callingCode": 996,
    "flag": "🇰🇬",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "ky",
      "ru"
    ]
  },
  {
    "code": "LA",
    "name": "Laos",
    "native": "ສປປລາວ",
    "callingCode": 856,
    "flag": "🇱🇦",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "lo"
    ]
  },
  {
    "code": "LV",
    "name": "Latvia",
    "native": "Latvija",
    "callingCode": 371,
    "flag": "🇱🇻",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "lv"
    ]
  },
  {
    "code": "LB",
    "name": "Lebanon",
    "native": "لبنان",
    "callingCode": 961,
    "flag": "🇱🇧",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "ar",
      "fr"
    ]
  },
  {
    "code": "LS",
    "name": "Lesotho",
    "native": "Lesotho",
    "callingCode": 266,
    "flag": "🇱🇸",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "en",
      "st"
    ]
  },
  {
    "code": "LR",
    "name": "Liberia",
    "native": "Liberia",
    "callingCode": 231,
    "flag": "🇱🇷",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "en"
    ]
  },
  {
    "code": "LY",
    "name": "Libya",
    "native": "‏ليبيا",
    "callingCode": 218,
    "flag": "🇱🇾",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "ar"
    ]
  },
  {
    "code": "LI",
    "name": "Liechtenstein",
    "native": "Liechtenstein",
    "callingCode": 423,
    "flag": "🇱🇮",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "de"
    ]
  },
  {
    "code": "LT",
    "name": "Lithuania",
    "native": "Lietuva",
    "callingCode": 370,
    "flag": "🇱🇹",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "lt"
    ]
  },
  {
    "code": "LU",
    "name": "Luxembourg",
    "native": "Luxembourg",
    "callingCode": 352,
    "flag": "🇱🇺",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "fr",
      "de",
      "lb"
    ]
  },
  {
    "code": "MO",
    "name": "Macao",
    "native": "澳門",
    "callingCode": 853,
    "flag": "🇲🇴",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "zh",
      "pt"
    ]
  },
  {
    "code": "MG",
    "name": "Madagascar",
    "native": "Madagasikara",
    "callingCode": 261,
    "flag": "🇲🇬",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "fr",
      "mg"
    ]
  },
  {
    "code": "MW",
    "name": "Malawi",
    "native": "Malawi",
    "callingCode": 265,
    "flag": "🇲🇼",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "en",
      "ny"
    ]
  },
  {
    "code": "MY",
    "name": "Malaysia",
    "native": "Malaysia",
    "callingCode": 60,
    "flag": "🇲🇾",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "ms"
    ]
  },
  {
    "code": "MV",
    "name": "Maldives",
    "native": "Maldives",
    "callingCode": 960,
    "flag": "🇲🇻",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "dv"
    ]
  },
  {
    "code": "ML",
    "name": "Mali",
    "native": "Mali",
    "callingCode": 223,
    "flag": "🇲🇱",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "fr"
    ]
  },
  {
    "code": "MT",
    "name": "Malta",
    "native": "Malta",
    "callingCode": 356,
    "flag": "🇲🇹",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "mt",
      "en"
    ]
  },
  {
    "code": "MH",
    "name": "Marshall Islands",
    "native": "M̧ajeļ",
    "callingCode": 692,
    "flag": "🇲🇭",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "en",
      "mh"
    ]
  },
  {
    "code": "MQ",
    "name": "Martinique",
    "native": "Martinique",
    "callingCode": 596,
    "flag": "🇲🇶",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "fr"
    ]
  },
  {
    "code": "MR",
    "name": "Mauritania",
    "native": "موريتانيا",
    "callingCode": 222,
    "flag": "🇲🇷",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "ar"
    ]
  },
  {
    "code": "MU",
    "name": "Mauritius",
    "native": "Maurice",
    "callingCode": 230,
    "flag": "🇲🇺",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "en"
    ]
  },
  {
    "code": "YT",
    "name": "Mayotte",
    "native": "Mayotte",
    "callingCode": 262,
    "flag": "🇾🇹",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "fr"
    ]
  },
  {
    "code": "MX",
    "name": "Mexico",
    "native": "México",
    "callingCode": 52,
    "flag": "🇲🇽",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "es"
    ]
  },
  {
    "code": "FM",
    "name": "Micronesia",
    "native": "Micronesia",
    "callingCode": 691,
    "flag": "🇫🇲",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "en"
    ]
  },
  {
    "code": "MD",
    "name": "Moldova",
    "native": "Moldova",
    "callingCode": 373,
    "flag": "🇲🇩",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "ro"
    ]
  },
  {
    "code": "MC",
    "name": "Monaco",
    "native": "Monaco",
    "callingCode": 377,
    "flag": "🇲🇨",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "fr"
    ]
  },
  {
    "code": "MN",
    "name": "Mongolia",
    "native": "Монгол улс",
    "callingCode": 976,
    "flag": "🇲🇳",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "mn"
    ]
  },
  {
    "code": "ME",
    "name": "Montenegro",
    "native": "Црна Гора",
    "callingCode": 382,
    "flag": "🇲🇪",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "sr",
      "bs",
      "sq",
      "hr"
    ]
  },
  {
    "code": "MS",
    "name": "Montserrat",
    "native": "Montserrat",
    "callingCode": 1664,
    "flag": "🇲🇸",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "en"
    ]
  },
  {
    "code": "MA",
    "name": "Morocco",
    "native": "المغرب",
    "callingCode": 212,
    "flag": "🇲🇦",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "ar"
    ]
  },
  {
    "code": "MZ",
    "name": "Mozambique",
    "native": "Moçambique",
    "callingCode": 258,
    "flag": "🇲🇿",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "pt"
    ]
  },
  {
    "code": "MM",
    "name": "Myanmar (Burma)",
    "native": "မြန်မာ",
    "callingCode": 95,
    "flag": "🇲🇲",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "my"
    ]
  },
  {
    "code": "NA",
    "name": "Namibia",
    "native": "Namibia",
    "callingCode": 264,
    "flag": "🇳🇦",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "en",
      "af"
    ]
  },
  {
    "code": "NR",
    "name": "Nauru",
    "native": "Nauru",
    "callingCode": 674,
    "flag": "🇳🇷",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "en",
      "na"
    ]
  },
  {
    "code": "NP",
    "name": "Nepal",
    "native": "नेपाल",
    "callingCode": 977,
    "flag": "🇳🇵",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "ne"
    ]
  },
  {
    "code": "NL",
    "name": "Netherlands",
    "native": "Nederland",
    "callingCode": 31,
    "flag": "🇳🇱",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "nl"
    ]
  },
  {
    "code": "NC",
    "name": "New Caledonia",
    "native": "Nouvelle-Calédonie",
    "callingCode": 687,
    "flag": "🇳🇨",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "fr"
    ]
  },
  {
    "code": "NZ",
    "name": "New Zealand",
    "native": "New Zealand",
    "callingCode": 64,
    "flag": "🇳🇿",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "en",
      "mi"
    ]
  },
  {
    "code": "NI",
    "name": "Nicaragua",
    "native": "Nicaragua",
    "callingCode": 505,
    "flag": "🇳🇮",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "es"
    ]
  },
  {
    "code": "NE",
    "name": "Niger",
    "native": "Niger",
    "callingCode": 227,
    "flag": "🇳🇪",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "fr"
    ]
  },
  {
    "code": "NG",
    "name": "Nigeria",
    "native": "Nigeria",
    "callingCode": 234,
    "flag": "🇳🇬",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "en"
    ]
  },
  {
    "code": "NU",
    "name": "Niue",
    "native": "Niuē",
    "callingCode": 683,
    "flag": "🇳🇺",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "en"
    ]
  },
  {
    "code": "NF",
    "name": "Norfolk Island",
    "native": "Norfolk Island",
    "callingCode": 672,
    "flag": "🇳🇫",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "en"
    ]
  },
  {
    "code": "KP",
    "name": "North Korea",
    "native": "북한",
    "callingCode": 850,
    "flag": "🇰🇵",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "ko"
    ]
  },
  {
    "code": "MK",
    "name": "North Macedonia",
    "native": "Северна Македонија",
    "callingCode": 389,
    "flag": "🇲🇰",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "mk"
    ]
  },
  {
    "code": "MP",
    "name": "Northern Mariana Islands",
    "native": "Northern Mariana Islands",
    "callingCode": 1670,
    "flag": "🇲🇵",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "en",
      "ch"
    ]
  },
  {
    "code": "NO",
    "name": "Norway",
    "native": "Norge",
    "callingCode": 47,
    "flag": "🇳🇴",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "no",
      "nb",
      "nn"
    ]
  },
  {
    "code": "OM",
    "name": "Oman",
    "native": "عمان",
    "callingCode": 968,
    "flag": "🇴🇲",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "ar"
    ]
  },
  {
    "code": "PK",
    "name": "Pakistan",
    "native": "Pakistan",
    "callingCode": 92,
    "flag": "🇵🇰",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "en",
      "ur"
    ]
  },
  {
    "code": "PW",
    "name": "Palau",
    "native": "Palau",
    "callingCode": 680,
    "flag": "🇵🇼",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "en"
    ]
  },
  {
    "code": "PS",
    "name": "Palestine",
    "native": "فلسطين",
    "callingCode": 970,
    "flag": "🇵🇸",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "ar"
    ]
  },
  {
    "code": "PA",
    "name": "Panama",
    "native": "Panamá",
    "callingCode": 507,
    "flag": "🇵🇦",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "es"
    ]
  },
  {
    "code": "PG",
    "name": "Papua New Guinea",
    "native": "Papua Niugini",
    "callingCode": 675,
    "flag": "🇵🇬",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "en"
    ]
  },
  {
    "code": "PY",
    "name": "Paraguay",
    "native": "Paraguay",
    "callingCode": 595,
    "flag": "🇵🇾",
    "continent": "SA",
    "continentName": "South America",
    "languages": [
      "es",
      "gn"
    ]
  },
  {
    "code": "PE",
    "name": "Peru",
    "native": "Perú",
    "callingCode": 51,
    "flag": "🇵🇪",
    "continent": "SA",
    "continentName": "South America",
    "languages": [
      "es"
    ]
  },
  {
    "code": "PH",
    "name": "Philippines",
    "native": "Pilipinas",
    "callingCode": 63,
    "flag": "🇵🇭",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "en",
      "tl"
    ]
  },
  {
    "code": "PN",
    "name": "Pitcairn Islands",
    "native": "Pitcairn Islands",
    "callingCode": 64,
    "flag": "🇵🇳",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "en"
    ]
  },
  {
    "code": "PL",
    "name": "Poland",
    "native": "Polska",
    "callingCode": 48,
    "flag": "🇵🇱",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "pl"
    ]
  },
  {
    "code": "PT",
    "name": "Portugal",
    "native": "Portugal",
    "callingCode": 351,
    "flag": "🇵🇹",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "pt"
    ]
  },
  {
    "code": "PR",
    "name": "Puerto Rico",
    "native": "Puerto Rico",
    "callingCode": 1787,
    "flag": "🇵🇷",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "es",
      "en"
    ]
  },
  {
    "code": "QA",
    "name": "Qatar",
    "native": "قطر",
    "callingCode": 974,
    "flag": "🇶🇦",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "ar"
    ]
  },
  {
    "code": "CG",
    "name": "Republic of the Congo",
    "native": "République du Congo",
    "callingCode": 242,
    "flag": "🇨🇬",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "fr",
      "ln"
    ]
  },
  {
    "code": "RE",
    "name": "Reunion",
    "native": "La Réunion",
    "callingCode": 262,
    "flag": "🇷🇪",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "fr"
    ]
  },
  {
    "code": "RO",
    "name": "Romania",
    "native": "România",
    "callingCode": 40,
    "flag": "🇷🇴",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "ro"
    ]
  },
  {
    "code": "RU",
    "name": "Russia",
    "native": "Россия",
    "callingCode": 7,
    "flag": "🇷🇺",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "ru"
    ]
  },
  {
    "code": "RW",
    "name": "Rwanda",
    "native": "Rwanda",
    "callingCode": 250,
    "flag": "🇷🇼",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "rw",
      "en",
      "fr"
    ]
  },
  {
    "code": "BL",
    "name": "Saint Barthelemy",
    "native": "Saint-Barthélemy",
    "callingCode": 590,
    "flag": "🇧🇱",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "fr"
    ]
  },
  {
    "code": "SH",
    "name": "Saint Helena",
    "native": "Saint Helena",
    "callingCode": 290,
    "flag": "🇸🇭",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "en"
    ]
  },
  {
    "code": "KN",
    "name": "Saint Kitts and Nevis",
    "native": "Saint Kitts and Nevis",
    "callingCode": 1869,
    "flag": "🇰🇳",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "en"
    ]
  },
  {
    "code": "LC",
    "name": "Saint Lucia",
    "native": "Saint Lucia",
    "callingCode": 1758,
    "flag": "🇱🇨",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "en"
    ]
  },
  {
    "code": "MF",
    "name": "Saint Martin",
    "native": "Saint-Martin",
    "callingCode": 590,
    "flag": "🇲🇫",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "en",
      "fr",
      "nl"
    ]
  },
  {
    "code": "PM",
    "name": "Saint Pierre and Miquelon",
    "native": "Saint-Pierre-et-Miquelon",
    "callingCode": 508,
    "flag": "🇵🇲",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "fr"
    ]
  },
  {
    "code": "VC",
    "name": "Saint Vincent and the Grenadines",
    "native": "Saint Vincent and the Grenadines",
    "callingCode": 1784,
    "flag": "🇻🇨",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "en"
    ]
  },
  {
    "code": "WS",
    "name": "Samoa",
    "native": "Samoa",
    "callingCode": 685,
    "flag": "🇼🇸",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "sm",
      "en"
    ]
  },
  {
    "code": "SM",
    "name": "San Marino",
    "native": "San Marino",
    "callingCode": 378,
    "flag": "🇸🇲",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "it"
    ]
  },
  {
    "code": "ST",
    "name": "Sao Tome and Principe",
    "native": "São Tomé e Príncipe",
    "callingCode": 239,
    "flag": "🇸🇹",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "pt"
    ]
  },
  {
    "code": "SA",
    "name": "Saudi Arabia",
    "native": "المملكة العربية السعودية",
    "callingCode": 966,
    "flag": "🇸🇦",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "ar"
    ]
  },
  {
    "code": "SN",
    "name": "Senegal",
    "native": "Sénégal",
    "callingCode": 221,
    "flag": "🇸🇳",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "fr"
    ]
  },
  {
    "code": "RS",
    "name": "Serbia",
    "native": "Србија",
    "callingCode": 381,
    "flag": "🇷🇸",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "sr"
    ]
  },
  {
    "code": "SC",
    "name": "Seychelles",
    "native": "Seychelles",
    "callingCode": 248,
    "flag": "🇸🇨",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "fr",
      "en"
    ]
  },
  {
    "code": "SL",
    "name": "Sierra Leone",
    "native": "Sierra Leone",
    "callingCode": 232,
    "flag": "🇸🇱",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "en"
    ]
  },
  {
    "code": "SG",
    "name": "Singapore",
    "native": "Singapore",
    "callingCode": 65,
    "flag": "🇸🇬",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "en",
      "ms",
      "ta",
      "zh"
    ]
  },
  {
    "code": "SX",
    "name": "Sint Maarten",
    "native": "Sint Maarten",
    "callingCode": 1721,
    "flag": "🇸🇽",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "nl",
      "en"
    ]
  },
  {
    "code": "SK",
    "name": "Slovakia",
    "native": "Slovensko",
    "callingCode": 421,
    "flag": "🇸🇰",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "sk"
    ]
  },
  {
    "code": "SI",
    "name": "Slovenia",
    "native": "Slovenija",
    "callingCode": 386,
    "flag": "🇸🇮",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "sl"
    ]
  },
  {
    "code": "SB",
    "name": "Solomon Islands",
    "native": "Solomon Islands",
    "callingCode": 677,
    "flag": "🇸🇧",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "en"
    ]
  },
  {
    "code": "SO",
    "name": "Somalia",
    "native": "Soomaaliya",
    "callingCode": 252,
    "flag": "🇸🇴",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "so",
      "ar"
    ]
  },
  {
    "code": "ZA",
    "name": "South Africa",
    "native": "South Africa",
    "callingCode": 27,
    "flag": "🇿🇦",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "af",
      "en",
      "nr",
      "st",
      "ss",
      "tn",
      "ts",
      "ve",
      "xh",
      "zu"
    ]
  },
  {
    "code": "GS",
    "name": "South Georgia and the South Sandwich Islands",
    "native": "South Georgia",
    "callingCode": 500,
    "flag": "🇬🇸",
    "continent": "AN",
    "continentName": "Antarctica",
    "languages": [
      "en"
    ]
  },
  {
    "code": "KR",
    "name": "South Korea",
    "native": "대한민국",
    "callingCode": 82,
    "flag": "🇰🇷",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "ko"
    ]
  },
  {
    "code": "SS",
    "name": "South Sudan",
    "native": "South Sudan",
    "callingCode": 211,
    "flag": "🇸🇸",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "en"
    ]
  },
  {
    "code": "ES",
    "name": "Spain",
    "native": "España",
    "callingCode": 34,
    "flag": "🇪🇸",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "es",
      "eu",
      "ca",
      "gl",
      "oc"
    ]
  },
  {
    "code": "LK",
    "name": "Sri Lanka",
    "native": "śrī laṃkāva",
    "callingCode": 94,
    "flag": "🇱🇰",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "si",
      "ta"
    ]
  },
  {
    "code": "SD",
    "name": "Sudan",
    "native": "السودان",
    "callingCode": 249,
    "flag": "🇸🇩",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "ar",
      "en"
    ]
  },
  {
    "code": "SR",
    "name": "Suriname",
    "native": "Suriname",
    "callingCode": 597,
    "flag": "🇸🇷",
    "continent": "SA",
    "continentName": "South America",
    "languages": [
      "nl"
    ]
  },
  {
    "code": "SJ",
    "name": "Svalbard and Jan Mayen",
    "native": "Svalbard og Jan Mayen",
    "callingCode": 4779,
    "flag": "🇸🇯",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "no"
    ]
  },
  {
    "code": "SE",
    "name": "Sweden",
    "native": "Sverige",
    "callingCode": 46,
    "flag": "🇸🇪",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "sv"
    ]
  },
  {
    "code": "CH",
    "name": "Switzerland",
    "native": "Schweiz",
    "callingCode": 41,
    "flag": "🇨🇭",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "de",
      "fr",
      "it"
    ]
  },
  {
    "code": "SY",
    "name": "Syria",
    "native": "سوريا",
    "callingCode": 963,
    "flag": "🇸🇾",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "ar"
    ]
  },
  {
    "code": "TW",
    "name": "Taiwan",
    "native": "臺灣",
    "callingCode": 886,
    "flag": "🇹🇼",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "zh"
    ]
  },
  {
    "code": "TJ",
    "name": "Tajikistan",
    "native": "Тоҷикистон",
    "callingCode": 992,
    "flag": "🇹🇯",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "tg",
      "ru"
    ]
  },
  {
    "code": "TZ",
    "name": "Tanzania",
    "native": "Tanzania",
    "callingCode": 255,
    "flag": "🇹🇿",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "sw",
      "en"
    ]
  },
  {
    "code": "TH",
    "name": "Thailand",
    "native": "ประเทศไทย",
    "callingCode": 66,
    "flag": "🇹🇭",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "th"
    ]
  },
  {
    "code": "TG",
    "name": "Togo",
    "native": "Togo",
    "callingCode": 228,
    "flag": "🇹🇬",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "fr"
    ]
  },
  {
    "code": "TK",
    "name": "Tokelau",
    "native": "Tokelau",
    "callingCode": 690,
    "flag": "🇹🇰",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "en"
    ]
  },
  {
    "code": "TO",
    "name": "Tonga",
    "native": "Tonga",
    "callingCode": 676,
    "flag": "🇹🇴",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "en",
      "to"
    ]
  },
  {
    "code": "TT",
    "name": "Trinidad and Tobago",
    "native": "Trinidad and Tobago",
    "callingCode": 1868,
    "flag": "🇹🇹",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "en"
    ]
  },
  {
    "code": "TA",
    "name": "Tristan da Cunha",
    "native": "Tristan da Cunha",
    "callingCode": 290,
    "flag": "🇹🇦",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "en"
    ]
  },
  {
    "code": "TN",
    "name": "Tunisia",
    "native": "تونس",
    "callingCode": 216,
    "flag": "🇹🇳",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "ar"
    ]
  },
  {
    "code": "TR",
    "name": "Türkiye",
    "native": "Türkiye",
    "callingCode": 90,
    "flag": "🇹🇷",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "tr"
    ]
  },
  {
    "code": "TM",
    "name": "Turkmenistan",
    "native": "Türkmenistan",
    "callingCode": 993,
    "flag": "🇹🇲",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "tk",
      "ru"
    ]
  },
  {
    "code": "TC",
    "name": "Turks and Caicos Islands",
    "native": "Turks and Caicos Islands",
    "callingCode": 1649,
    "flag": "🇹🇨",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "en"
    ]
  },
  {
    "code": "TV",
    "name": "Tuvalu",
    "native": "Tuvalu",
    "callingCode": 688,
    "flag": "🇹🇻",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "en"
    ]
  },
  {
    "code": "UM",
    "name": "U.S. Minor Outlying Islands",
    "native": "United States Minor Outlying Islands",
    "callingCode": 1,
    "flag": "🇺🇲",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "en"
    ]
  },
  {
    "code": "VI",
    "name": "U.S. Virgin Islands",
    "native": "United States Virgin Islands",
    "callingCode": 1340,
    "flag": "🇻🇮",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "en"
    ]
  },
  {
    "code": "UG",
    "name": "Uganda",
    "native": "Uganda",
    "callingCode": 256,
    "flag": "🇺🇬",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "en",
      "sw"
    ]
  },
  {
    "code": "UA",
    "name": "Ukraine",
    "native": "Україна",
    "callingCode": 380,
    "flag": "🇺🇦",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "uk"
    ]
  },
  {
    "code": "AE",
    "name": "United Arab Emirates",
    "native": "دولة الإمارات العربية المتحدة",
    "callingCode": 971,
    "flag": "🇦🇪",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "ar"
    ]
  },
  {
    "code": "GB",
    "name": "United Kingdom",
    "native": "United Kingdom",
    "callingCode": 44,
    "flag": "🇬🇧",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "en"
    ]
  },
  {
    "code": "US",
    "name": "United States",
    "native": "United States",
    "callingCode": 1,
    "flag": "🇺🇸",
    "continent": "NA",
    "continentName": "North America",
    "languages": [
      "en"
    ]
  },
  {
    "code": "UY",
    "name": "Uruguay",
    "native": "Uruguay",
    "callingCode": 598,
    "flag": "🇺🇾",
    "continent": "SA",
    "continentName": "South America",
    "languages": [
      "es"
    ]
  },
  {
    "code": "UZ",
    "name": "Uzbekistan",
    "native": "O'zbekiston",
    "callingCode": 998,
    "flag": "🇺🇿",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "uz",
      "ru"
    ]
  },
  {
    "code": "VU",
    "name": "Vanuatu",
    "native": "Vanuatu",
    "callingCode": 678,
    "flag": "🇻🇺",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "bi",
      "en",
      "fr"
    ]
  },
  {
    "code": "VA",
    "name": "Vatican City",
    "native": "Vaticano",
    "callingCode": 379,
    "flag": "🇻🇦",
    "continent": "EU",
    "continentName": "Europe",
    "languages": [
      "it",
      "la"
    ]
  },
  {
    "code": "VE",
    "name": "Venezuela",
    "native": "Venezuela",
    "callingCode": 58,
    "flag": "🇻🇪",
    "continent": "SA",
    "continentName": "South America",
    "languages": [
      "es"
    ]
  },
  {
    "code": "VN",
    "name": "Vietnam",
    "native": "Việt Nam",
    "callingCode": 84,
    "flag": "🇻🇳",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "vi"
    ]
  },
  {
    "code": "WF",
    "name": "Wallis and Futuna",
    "native": "Wallis et Futuna",
    "callingCode": 681,
    "flag": "🇼🇫",
    "continent": "OC",
    "continentName": "Oceania",
    "languages": [
      "fr"
    ]
  },
  {
    "code": "EH",
    "name": "Western Sahara",
    "native": "الصحراء الغربية",
    "callingCode": 212,
    "flag": "🇪🇭",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "es"
    ]
  },
  {
    "code": "YE",
    "name": "Yemen",
    "native": "اليَمَن",
    "callingCode": 967,
    "flag": "🇾🇪",
    "continent": "AS",
    "continentName": "Asia",
    "languages": [
      "ar"
    ]
  },
  {
    "code": "ZM",
    "name": "Zambia",
    "native": "Zambia",
    "callingCode": 260,
    "flag": "🇿🇲",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "en"
    ]
  },
  {
    "code": "ZW",
    "name": "Zimbabwe",
    "native": "Zimbabwe",
    "callingCode": 263,
    "flag": "🇿🇼",
    "continent": "AF",
    "continentName": "Africa",
    "languages": [
      "en",
      "sn",
      "nd"
    ]
  }
] as const;

export const LANGUAGES: readonly LanguageInfo[] = [
  {
    "code": "ab",
    "name": "Abkhazian",
    "native": "Аҧсуа",
    "rtl": false
  },
  {
    "code": "aa",
    "name": "Afar",
    "native": "Afar",
    "rtl": false
  },
  {
    "code": "af",
    "name": "Afrikaans",
    "native": "Afrikaans",
    "rtl": false
  },
  {
    "code": "ak",
    "name": "Akan",
    "native": "Akana",
    "rtl": false
  },
  {
    "code": "sq",
    "name": "Albanian",
    "native": "Shqip",
    "rtl": false
  },
  {
    "code": "am",
    "name": "Amharic",
    "native": "አማርኛ",
    "rtl": false
  },
  {
    "code": "ar",
    "name": "Arabic",
    "native": "العربية",
    "rtl": true
  },
  {
    "code": "an",
    "name": "Aragonese",
    "native": "Aragonés",
    "rtl": false
  },
  {
    "code": "hy",
    "name": "Armenian",
    "native": "Հայերեն",
    "rtl": false
  },
  {
    "code": "as",
    "name": "Assamese",
    "native": "অসমীয়া",
    "rtl": false
  },
  {
    "code": "av",
    "name": "Avar",
    "native": "Авар",
    "rtl": false
  },
  {
    "code": "ay",
    "name": "Aymara",
    "native": "Aymar",
    "rtl": false
  },
  {
    "code": "az",
    "name": "Azerbaijani",
    "native": "Azərbaycanca / آذربايجان",
    "rtl": false
  },
  {
    "code": "bm",
    "name": "Bambara",
    "native": "Bamanankan",
    "rtl": false
  },
  {
    "code": "ba",
    "name": "Bashkir",
    "native": "Башҡорт",
    "rtl": false
  },
  {
    "code": "eu",
    "name": "Basque",
    "native": "Euskara",
    "rtl": false
  },
  {
    "code": "be",
    "name": "Belarusian",
    "native": "Беларуская",
    "rtl": false
  },
  {
    "code": "bn",
    "name": "Bengali",
    "native": "বাংলা",
    "rtl": false
  },
  {
    "code": "bh",
    "name": "Bihari",
    "native": "भोजपुरी",
    "rtl": false
  },
  {
    "code": "bi",
    "name": "Bislama",
    "native": "Bislama",
    "rtl": false
  },
  {
    "code": "bs",
    "name": "Bosnian",
    "native": "Bosanski",
    "rtl": false
  },
  {
    "code": "br",
    "name": "Breton",
    "native": "Brezhoneg",
    "rtl": false
  },
  {
    "code": "bg",
    "name": "Bulgarian",
    "native": "Български",
    "rtl": false
  },
  {
    "code": "my",
    "name": "Burmese",
    "native": "မြန်မာစာ",
    "rtl": false
  },
  {
    "code": "km",
    "name": "Cambodian",
    "native": "ភាសាខ្មែរ",
    "rtl": false
  },
  {
    "code": "ca",
    "name": "Catalan",
    "native": "Català",
    "rtl": false
  },
  {
    "code": "ch",
    "name": "Chamorro",
    "native": "Chamoru",
    "rtl": false
  },
  {
    "code": "ce",
    "name": "Chechen",
    "native": "Нохчийн",
    "rtl": false
  },
  {
    "code": "ny",
    "name": "Chichewa",
    "native": "Chi-Chewa",
    "rtl": false
  },
  {
    "code": "zh",
    "name": "Chinese",
    "native": "中文",
    "rtl": false
  },
  {
    "code": "cv",
    "name": "Chuvash",
    "native": "Чăваш",
    "rtl": false
  },
  {
    "code": "kw",
    "name": "Cornish",
    "native": "Kernewek",
    "rtl": false
  },
  {
    "code": "co",
    "name": "Corsican",
    "native": "Corsu",
    "rtl": false
  },
  {
    "code": "cr",
    "name": "Cree",
    "native": "Nehiyaw",
    "rtl": false
  },
  {
    "code": "hr",
    "name": "Croatian",
    "native": "Hrvatski",
    "rtl": false
  },
  {
    "code": "cs",
    "name": "Czech",
    "native": "Čeština",
    "rtl": false
  },
  {
    "code": "da",
    "name": "Danish",
    "native": "Dansk",
    "rtl": false
  },
  {
    "code": "dv",
    "name": "Divehi",
    "native": "ދިވެހިބަސް",
    "rtl": true
  },
  {
    "code": "nl",
    "name": "Dutch",
    "native": "Nederlands",
    "rtl": false
  },
  {
    "code": "dz",
    "name": "Dzongkha",
    "native": "ཇོང་ཁ",
    "rtl": false
  },
  {
    "code": "en",
    "name": "English",
    "native": "English",
    "rtl": false
  },
  {
    "code": "eo",
    "name": "Esperanto",
    "native": "Esperanto",
    "rtl": false
  },
  {
    "code": "et",
    "name": "Estonian",
    "native": "Eesti",
    "rtl": false
  },
  {
    "code": "ee",
    "name": "Ewe",
    "native": "Ɛʋɛ",
    "rtl": false
  },
  {
    "code": "fo",
    "name": "Faroese",
    "native": "Føroyskt",
    "rtl": false
  },
  {
    "code": "fj",
    "name": "Fijian",
    "native": "Na Vosa Vakaviti",
    "rtl": false
  },
  {
    "code": "fi",
    "name": "Finnish",
    "native": "Suomi",
    "rtl": false
  },
  {
    "code": "fr",
    "name": "French",
    "native": "Français",
    "rtl": false
  },
  {
    "code": "gl",
    "name": "Galician",
    "native": "Galego",
    "rtl": false
  },
  {
    "code": "lg",
    "name": "Ganda",
    "native": "Luganda",
    "rtl": false
  },
  {
    "code": "ka",
    "name": "Georgian",
    "native": "ქართული",
    "rtl": false
  },
  {
    "code": "de",
    "name": "German",
    "native": "Deutsch",
    "rtl": false
  },
  {
    "code": "el",
    "name": "Greek",
    "native": "Ελληνικά",
    "rtl": false
  },
  {
    "code": "kl",
    "name": "Greenlandic",
    "native": "Kalaallisut",
    "rtl": false
  },
  {
    "code": "gn",
    "name": "Guarani",
    "native": "Avañe'ẽ",
    "rtl": false
  },
  {
    "code": "gu",
    "name": "Gujarati",
    "native": "ગુજરાતી",
    "rtl": false
  },
  {
    "code": "ht",
    "name": "Haitian",
    "native": "Krèyol ayisyen",
    "rtl": false
  },
  {
    "code": "ha",
    "name": "Hausa",
    "native": "هَوُسَ",
    "rtl": true
  },
  {
    "code": "he",
    "name": "Hebrew",
    "native": "עברית",
    "rtl": true
  },
  {
    "code": "hz",
    "name": "Herero",
    "native": "Otsiherero",
    "rtl": false
  },
  {
    "code": "hi",
    "name": "Hindi",
    "native": "हिन्दी",
    "rtl": false
  },
  {
    "code": "ho",
    "name": "Hiri Motu",
    "native": "Hiri Motu",
    "rtl": false
  },
  {
    "code": "hu",
    "name": "Hungarian",
    "native": "Magyar",
    "rtl": false
  },
  {
    "code": "is",
    "name": "Icelandic",
    "native": "Íslenska",
    "rtl": false
  },
  {
    "code": "io",
    "name": "Ido",
    "native": "Ido",
    "rtl": false
  },
  {
    "code": "ig",
    "name": "Igbo",
    "native": "Igbo",
    "rtl": false
  },
  {
    "code": "id",
    "name": "Indonesian",
    "native": "Bahasa Indonesia",
    "rtl": false
  },
  {
    "code": "ia",
    "name": "Interlingua",
    "native": "Interlingua",
    "rtl": false
  },
  {
    "code": "ie",
    "name": "Interlingue",
    "native": "Interlingue",
    "rtl": false
  },
  {
    "code": "iu",
    "name": "Inuktitut",
    "native": "ᐃᓄᒃᑎᑐᑦ",
    "rtl": false
  },
  {
    "code": "ik",
    "name": "Inupiak",
    "native": "Iñupiak",
    "rtl": false
  },
  {
    "code": "ga",
    "name": "Irish",
    "native": "Gaeilge",
    "rtl": false
  },
  {
    "code": "it",
    "name": "Italian",
    "native": "Italiano",
    "rtl": false
  },
  {
    "code": "ja",
    "name": "Japanese",
    "native": "日本語",
    "rtl": false
  },
  {
    "code": "jv",
    "name": "Javanese",
    "native": "Basa Jawa",
    "rtl": false
  },
  {
    "code": "kn",
    "name": "Kannada",
    "native": "ಕನ್ನಡ",
    "rtl": false
  },
  {
    "code": "kr",
    "name": "Kanuri",
    "native": "Kanuri",
    "rtl": false
  },
  {
    "code": "ks",
    "name": "Kashmiri",
    "native": "कश्मीरी / كشميري",
    "rtl": true
  },
  {
    "code": "kk",
    "name": "Kazakh",
    "native": "Қазақша",
    "rtl": false
  },
  {
    "code": "ki",
    "name": "Kikuyu",
    "native": "Gĩkũyũ",
    "rtl": false
  },
  {
    "code": "rn",
    "name": "Kirundi",
    "native": "Kirundi",
    "rtl": false
  },
  {
    "code": "kv",
    "name": "Komi",
    "native": "Коми",
    "rtl": false
  },
  {
    "code": "kg",
    "name": "Kongo",
    "native": "KiKongo",
    "rtl": false
  },
  {
    "code": "ko",
    "name": "Korean",
    "native": "한국어",
    "rtl": false
  },
  {
    "code": "kj",
    "name": "Kuanyama",
    "native": "Kuanyama",
    "rtl": false
  },
  {
    "code": "ku",
    "name": "Kurdish",
    "native": "Kurdî / كوردی",
    "rtl": true
  },
  {
    "code": "ky",
    "name": "Kyrgyz",
    "native": "Кыргызча",
    "rtl": false
  },
  {
    "code": "lo",
    "name": "Laotian",
    "native": "ລາວ / Pha xa lao",
    "rtl": false
  },
  {
    "code": "la",
    "name": "Latin",
    "native": "Latina",
    "rtl": false
  },
  {
    "code": "lv",
    "name": "Latvian",
    "native": "Latviešu",
    "rtl": false
  },
  {
    "code": "li",
    "name": "Limburgian",
    "native": "Limburgs",
    "rtl": false
  },
  {
    "code": "ln",
    "name": "Lingala",
    "native": "Lingála",
    "rtl": false
  },
  {
    "code": "lt",
    "name": "Lithuanian",
    "native": "Lietuvių",
    "rtl": false
  },
  {
    "code": "lu",
    "name": "Luba-Katanga",
    "native": "Tshiluba",
    "rtl": false
  },
  {
    "code": "lb",
    "name": "Luxembourgish",
    "native": "Lëtzebuergesch",
    "rtl": false
  },
  {
    "code": "mk",
    "name": "Macedonian",
    "native": "Македонски",
    "rtl": false
  },
  {
    "code": "mg",
    "name": "Malagasy",
    "native": "Malagasy",
    "rtl": false
  },
  {
    "code": "ms",
    "name": "Malay",
    "native": "Bahasa Melayu",
    "rtl": false
  },
  {
    "code": "ml",
    "name": "Malayalam",
    "native": "മലയാളം",
    "rtl": false
  },
  {
    "code": "mt",
    "name": "Maltese",
    "native": "bil-Malti",
    "rtl": false
  },
  {
    "code": "gv",
    "name": "Manx",
    "native": "Gaelg",
    "rtl": false
  },
  {
    "code": "mi",
    "name": "Maori",
    "native": "Māori",
    "rtl": false
  },
  {
    "code": "mr",
    "name": "Marathi",
    "native": "मराठी",
    "rtl": false
  },
  {
    "code": "mh",
    "name": "Marshallese",
    "native": "Kajin Majel / Ebon",
    "rtl": false
  },
  {
    "code": "mo",
    "name": "Moldovan",
    "native": "Moldovenească",
    "rtl": false
  },
  {
    "code": "mn",
    "name": "Mongolian",
    "native": "Монгол",
    "rtl": false
  },
  {
    "code": "na",
    "name": "Nauruan",
    "native": "Dorerin Naoero",
    "rtl": false
  },
  {
    "code": "nv",
    "name": "Navajo",
    "native": "Diné bizaad",
    "rtl": false
  },
  {
    "code": "ng",
    "name": "Ndonga",
    "native": "Oshiwambo",
    "rtl": false
  },
  {
    "code": "ne",
    "name": "Nepali",
    "native": "नेपाली",
    "rtl": false
  },
  {
    "code": "nd",
    "name": "North Ndebele",
    "native": "Sindebele",
    "rtl": false
  },
  {
    "code": "se",
    "name": "Northern Sami",
    "native": "Sámegiella",
    "rtl": false
  },
  {
    "code": "no",
    "name": "Norwegian",
    "native": "Norsk",
    "rtl": false
  },
  {
    "code": "nb",
    "name": "Norwegian Bokmål",
    "native": "Norsk bokmål",
    "rtl": false
  },
  {
    "code": "nn",
    "name": "Norwegian Nynorsk",
    "native": "Norsk nynorsk",
    "rtl": false
  },
  {
    "code": "oc",
    "name": "Occitan",
    "native": "Occitan",
    "rtl": false
  },
  {
    "code": "oj",
    "name": "Ojibwa",
    "native": "ᐊᓂᔑᓈᐯᒧᐎᓐ / Anishinaabemowin",
    "rtl": false
  },
  {
    "code": "cu",
    "name": "Old Church Slavonic / Old Bulgarian",
    "native": "словѣньскъ / slověnĭskŭ",
    "rtl": false
  },
  {
    "code": "or",
    "name": "Oriya",
    "native": "ଓଡ଼ିଆ",
    "rtl": false
  },
  {
    "code": "om",
    "name": "Oromo",
    "native": "Oromoo",
    "rtl": false
  },
  {
    "code": "os",
    "name": "Ossetian / Ossetic",
    "native": "Иронау",
    "rtl": false
  },
  {
    "code": "pi",
    "name": "Pali",
    "native": "Pāli / पाऴि",
    "rtl": false
  },
  {
    "code": "pa",
    "name": "Panjabi / Punjabi",
    "native": "ਪੰਜਾਬੀ / पंजाबी / پنجابي",
    "rtl": false
  },
  {
    "code": "ps",
    "name": "Pashto",
    "native": "پښتو",
    "rtl": true
  },
  {
    "code": "fa",
    "name": "Persian",
    "native": "فارسی",
    "rtl": true
  },
  {
    "code": "ff",
    "name": "Peul",
    "native": "Fulfulde",
    "rtl": false
  },
  {
    "code": "pl",
    "name": "Polish",
    "native": "Polski",
    "rtl": false
  },
  {
    "code": "pt",
    "name": "Portuguese",
    "native": "Português",
    "rtl": false
  },
  {
    "code": "qu",
    "name": "Quechua",
    "native": "Runa Simi",
    "rtl": false
  },
  {
    "code": "rm",
    "name": "Raeto Romance",
    "native": "Rumantsch",
    "rtl": false
  },
  {
    "code": "ro",
    "name": "Romanian",
    "native": "Română",
    "rtl": false
  },
  {
    "code": "ru",
    "name": "Russian",
    "native": "Русский",
    "rtl": false
  },
  {
    "code": "rw",
    "name": "Rwandi",
    "native": "Kinyarwandi",
    "rtl": false
  },
  {
    "code": "sm",
    "name": "Samoan",
    "native": "Gagana Samoa",
    "rtl": false
  },
  {
    "code": "sg",
    "name": "Sango",
    "native": "Sängö",
    "rtl": false
  },
  {
    "code": "sa",
    "name": "Sanskrit",
    "native": "संस्कृतम्",
    "rtl": false
  },
  {
    "code": "sc",
    "name": "Sardinian",
    "native": "Sardu",
    "rtl": false
  },
  {
    "code": "gd",
    "name": "Scottish Gaelic",
    "native": "Gàidhlig",
    "rtl": false
  },
  {
    "code": "sr",
    "name": "Serbian",
    "native": "Српски",
    "rtl": false
  },
  {
    "code": "sh",
    "name": "Serbo-Croatian",
    "native": "Srpskohrvatski / Српскохрватски",
    "rtl": false
  },
  {
    "code": "sn",
    "name": "Shona",
    "native": "chiShona",
    "rtl": false
  },
  {
    "code": "ii",
    "name": "Sichuan Yi",
    "native": "ꆇꉙ / 四川彝语",
    "rtl": false
  },
  {
    "code": "sd",
    "name": "Sindhi",
    "native": "सिनधि",
    "rtl": false
  },
  {
    "code": "si",
    "name": "Sinhalese",
    "native": "සිංහල",
    "rtl": false
  },
  {
    "code": "sk",
    "name": "Slovak",
    "native": "Slovenčina",
    "rtl": false
  },
  {
    "code": "sl",
    "name": "Slovenian",
    "native": "Slovenščina",
    "rtl": false
  },
  {
    "code": "so",
    "name": "Somalia",
    "native": "Soomaaliga",
    "rtl": false
  },
  {
    "code": "nr",
    "name": "South Ndebele",
    "native": "isiNdebele",
    "rtl": false
  },
  {
    "code": "st",
    "name": "Southern Sotho",
    "native": "Sesotho",
    "rtl": false
  },
  {
    "code": "es",
    "name": "Spanish",
    "native": "Español",
    "rtl": false
  },
  {
    "code": "su",
    "name": "Sundanese",
    "native": "Basa Sunda",
    "rtl": false
  },
  {
    "code": "sw",
    "name": "Swahili",
    "native": "Kiswahili",
    "rtl": false
  },
  {
    "code": "ss",
    "name": "Swati",
    "native": "SiSwati",
    "rtl": false
  },
  {
    "code": "sv",
    "name": "Swedish",
    "native": "Svenska",
    "rtl": false
  },
  {
    "code": "tl",
    "name": "Tagalog / Filipino",
    "native": "Tagalog",
    "rtl": false
  },
  {
    "code": "ty",
    "name": "Tahitian",
    "native": "Reo Mā`ohi",
    "rtl": false
  },
  {
    "code": "tg",
    "name": "Tajik",
    "native": "Тоҷикӣ",
    "rtl": false
  },
  {
    "code": "ta",
    "name": "Tamil",
    "native": "தமிழ்",
    "rtl": false
  },
  {
    "code": "tt",
    "name": "Tatar",
    "native": "Tatarça",
    "rtl": false
  },
  {
    "code": "te",
    "name": "Telugu",
    "native": "తెలుగు",
    "rtl": false
  },
  {
    "code": "th",
    "name": "Thai",
    "native": "ไทย / Phasa Thai",
    "rtl": false
  },
  {
    "code": "bo",
    "name": "Tibetan",
    "native": "བོད་ཡིག / Bod skad",
    "rtl": false
  },
  {
    "code": "ti",
    "name": "Tigrinya",
    "native": "ትግርኛ",
    "rtl": false
  },
  {
    "code": "to",
    "name": "Tonga",
    "native": "Lea Faka-Tonga",
    "rtl": false
  },
  {
    "code": "ts",
    "name": "Tsonga",
    "native": "Xitsonga",
    "rtl": false
  },
  {
    "code": "tn",
    "name": "Tswana",
    "native": "Setswana",
    "rtl": false
  },
  {
    "code": "tr",
    "name": "Turkish",
    "native": "Türkçe",
    "rtl": false
  },
  {
    "code": "tk",
    "name": "Turkmen",
    "native": "Туркмен / تركمن",
    "rtl": false
  },
  {
    "code": "tw",
    "name": "Twi",
    "native": "Twi",
    "rtl": false
  },
  {
    "code": "uk",
    "name": "Ukrainian",
    "native": "Українська",
    "rtl": false
  },
  {
    "code": "ur",
    "name": "Urdu",
    "native": "اردو",
    "rtl": true
  },
  {
    "code": "ug",
    "name": "Uyghur",
    "native": "Uyƣurqə / ئۇيغۇرچە",
    "rtl": false
  },
  {
    "code": "uz",
    "name": "Uzbek",
    "native": "O'zbekcha",
    "rtl": false
  },
  {
    "code": "ve",
    "name": "Venda",
    "native": "Tshivenḓa",
    "rtl": false
  },
  {
    "code": "vi",
    "name": "Vietnamese",
    "native": "Tiếng Việt",
    "rtl": false
  },
  {
    "code": "vo",
    "name": "Volapük",
    "native": "Volapük",
    "rtl": false
  },
  {
    "code": "wa",
    "name": "Walloon",
    "native": "Walon",
    "rtl": false
  },
  {
    "code": "cy",
    "name": "Welsh",
    "native": "Cymraeg",
    "rtl": false
  },
  {
    "code": "fy",
    "name": "West Frisian",
    "native": "Frysk",
    "rtl": false
  },
  {
    "code": "wo",
    "name": "Wolof",
    "native": "Wollof",
    "rtl": false
  },
  {
    "code": "xh",
    "name": "Xhosa",
    "native": "isiXhosa",
    "rtl": false
  },
  {
    "code": "yi",
    "name": "Yiddish",
    "native": "ייִדיש",
    "rtl": true
  },
  {
    "code": "yo",
    "name": "Yoruba",
    "native": "Yorùbá",
    "rtl": false
  },
  {
    "code": "za",
    "name": "Zhuang",
    "native": "Cuengh / Tôô / 壮语",
    "rtl": false
  },
  {
    "code": "zu",
    "name": "Zulu",
    "native": "isiZulu",
    "rtl": false
  }
] as const;
