services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: learnix-postgres
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: learnix
      POSTGRES_PASSWORD: learnix_dev_2024
      POSTGRES_DB: learnix
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-extensions.sql:/docker-entrypoint-initdb.d/init-extensions.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U learnix']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: learnix-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redisdata:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

  meilisearch:
    image: getmeili/meilisearch:v1.11
    container_name: learnix-meilisearch
    restart: unless-stopped
    ports:
      - '7700:7700'
    environment:
      MEILI_ENV: development
      MEILI_MASTER_KEY: learnix_meili_dev_key
      MEILI_NO_ANALYTICS: 'true'
    volumes:
      - meilidata:/meili_data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:7700/health']
      interval: 5s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    container_name: learnix-mailhog
    restart: unless-stopped
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  pgdata:
  redisdata:
  meilidata:
