/**
 * Build-time generator: emits packages/validation/src/geo.data.ts from the CLDR-derived
 * `countries-list` dataset so the runtime carries an embedded, dependency-free table of
 * every country (ISO alpha-2, calling code, flag, languages) and language (ISO 639-1,
 * English + native name, RTL flag). Re-run with: `node scripts/gen-geo.cjs`.
 */
const fs = require('node:fs');
const path = require('node:path');
const cl = require(path.join(__dirname, '..', 'packages', 'validation', 'node_modules', 'countries-list'));

const continentNames = cl.continents;

const countries = Object.entries(cl.countries)
  .map(([code, c]) => ({
    code,
    name: c.name,
    native: c.native,
    // A country can share a calling code region; store the primary.
    callingCode: Array.isArray(c.phone) ? c.phone[0] : c.phone,
    flag: cl.getEmojiFlag(code),
    continent: c.continent,
    continentName: continentNames[c.continent] ?? c.continent,
    languages: c.languages ?? [],
  }))
  .sort((a, b) => a.name.localeCompare(b.name));

const languages = Object.entries(cl.languages)
  .map(([code, l]) => ({
    code,
    name: l.name,
    native: l.native,
    rtl: l.rtl === 1 || l.rtl === true,
  }))
  .sort((a, b) => a.name.localeCompare(b.name));

const header = `// AUTO-GENERATED by scripts/gen-geo.cjs from the CLDR-derived \`countries-list\` dataset.
// Do not edit by hand. Global country + language reference for a worldwide audience.
// ${countries.length} countries · ${languages.length} languages.

export interface CountryInfo {
  code: string;          // ISO 3166-1 alpha-2 (e.g. "KE", "US", "IN")
  name: string;          // English name
  native: string;        // native name
  callingCode: number;   // E.164 country calling code (e.g. 254, 1, 91)
  flag: string;          // flag emoji
  continent: string;     // continent code (AF, EU, AS, NA, SA, OC, AN)
  continentName: string;
  languages: string[];   // ISO 639-1 codes spoken/official in the country
}

export interface LanguageInfo {
  code: string;   // ISO 639-1 (e.g. "en", "sw", "ar")
  name: string;   // English name
  native: string; // native name (e.g. "Kiswahili", "العربية")
  rtl: boolean;   // right-to-left script
}
`;

const body = `
export const COUNTRIES: readonly CountryInfo[] = ${JSON.stringify(countries, null, 2)} as const;

export const LANGUAGES: readonly LanguageInfo[] = ${JSON.stringify(languages, null, 2)} as const;
`;

const out = path.join(__dirname, '..', 'packages', 'validation', 'src', 'geo.data.ts');
fs.writeFileSync(out, header + body);
console.log(`Wrote ${out}: ${countries.length} countries, ${languages.length} languages`);
