services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: learnix-postgres
    environment:
      POSTGRES_USER: learnix
      POSTGRES_PASSWORD: learnix
      POSTGRES_DB: learnix
    ports:
      - '5432:5432'
    volumes:
      - learnix_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U learnix']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: learnix-redis
    ports:
      - '6379:6379'

  meilisearch:
    image: getmeili/meilisearch:v1.10
    container_name: learnix-meilisearch
    environment:
      MEILI_MASTER_KEY: learnix-dev-key
    ports:
      - '7700:7700'
    volumes:
      - learnix_meili:/meili_data

  mailhog:
    image: mailhog/mailhog
    container_name: learnix-mailhog
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  learnix_pgdata:
  learnix_meili:
